name: sodium_mr_agr_paper

channels:
  - conda-forge

dependencies:
  - sigpy==0.1.25 # sigpy currently needs numpy < 1.20 (np.float issue)
  - numpy<=1.19
  - cupy<=10.6 # new cupy versions need numpy >= 1.20
  - h5py>=3.0
  - matplotlib>=3.0
  - nibabel>=5.0
  - scipy>=1.0
  - SimpleITK>=2.0
  - pymirc
  - seaborn
